name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 配置 Git
        run: |
          git config --global user.name 'BoyuanJiang'
          git config --global user.email 'ginger188@gmail.com'
      
      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/BoyuanJiang/FitDiT.git
          
      - name: 同步分支
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/FitDiT-ComfyUI --allow-unrelated-histories
          git push origin main 